#!/bin/sh
operator=$1
MPWFOUNDATION=$2

$operator AccessorMacros.h $MPWFOUNDATION/Classes/AccessorMacros.h
$operator CodingAdditions.h $MPWFOUNDATION/Classes/CodingAdditions.h
$operator DebugMacros.h $MPWFOUNDATION/Classes/DebugMacros.h
$operator MPWCaseInsensitiveSmallStringTable.h $MPWFOUNDATION/Collections.subproj/MPWCaseInsensitiveSmallStringTable.h
$operator MPWCaseInsensitiveSmallStringTable.m $MPWFOUNDATION/Collections.subproj/MPWCaseInsensitiveSmallStringTable.m
$operator MPWFastInvocation.h $MPWFOUNDATION/Classes/MPWFastInvocation.h
$operator MPWFastInvocation.m $MPWFOUNDATION/Classes/MPWFastInvocation.m
$operator MPWObject.h $MPWFOUNDATION/Classes/MPWObject.h
$operator MPWObject.m $MPWFOUNDATION/Classes/MPWObject.m
$operator MPWObjectCache.h $MPWFOUNDATION/Classes/MPWObjectCache.h
$operator MPWObjectCache.m $MPWFOUNDATION/Classes/MPWObjectCache.m
$operator MPWSmallStringTable.h $MPWFOUNDATION/Collections.subproj/MPWSmallStringTable.h
$operator MPWSmallStringTable.m $MPWFOUNDATION/Collections.subproj/MPWSmallStringTable.m
$operator MPWSubData.h $MPWFOUNDATION/Collections.subproj/MPWSubData.h
$operator MPWSubData.m $MPWFOUNDATION/Collections.subproj/MPWSubData.m
$operator NSInvocationAdditions_lookup.h $MPWFOUNDATION/Classes/NSInvocationAdditions_lookup.h
$operator MPWObject_fastrc.h $MPWFOUNDATION/Classes/MPWObject_fastrc.h
